[package]
name = "gameboy-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
itertools = "0.13.0"
quote = "1.0.36"
thiserror = "1.0.61"

[lib]
proc-macro = true
